version: '3.8'

services:
  dex-adapter:
    build: .
    container_name: dex_adapter
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.http.routers.dexscreener.rule=Host(`dexadapter.gliquid.xyz`)
      - traefik.http.routers.dexscreener.entryPoints=https
      - traefik.http.routers.dexscreener.tls=true
      - traefik.http.routers.dexscreener.tls.certresolver=letsencrypt
      - traefik.http.services.dexscreener.loadbalancer.server.port=8000
      - traefik.docker.network=traefik
    networks:
      - traefik
networks:
  traefik:
    external: true